### ISSUE TITLE
Datapusher stuck with pending status 

### ISSUE THREAD

**Issue by sagargg** [dathere/datapusher-plus#100]
**Describe the bug**

Datapusher stuck with pending status,  when i check the datapusher log it's throwing the below error.
```
datapusher-plus  | During handling of the above exception, another exception occurred:
datapusher-plus  | 
datapusher-plus  | Traceback (most recent call last):
datapusher-plus  |   File "/usr/lib/ckan/dpplus_venv/lib/python3.10/site-packages/apscheduler/executors/base.py", line 125, in run_job
datapusher-plus  |     retval = job.func(*job.args, **job.kwargs)
datapusher-plus  |   File "/srv/app/src/datapusher-plus/datapusher/jobs.py", line 406, in push_to_datastore
datapusher-plus  |     raise util.JobError("Cannot parse qsv version info: {}".format(e))
datapusher-plus  | ckanserviceprovider.util.JobError: Cannot parse qsv version info:  is not valid SemVer string
datapusher-plus  | --- Logging error ---
datapusher-plus  | Traceback (most recent call last):
datapusher-plus  |   File "/srv/app/src/datapusher-plus/datapusher/jobs.py", line 399, in push_to_datastore
datapusher-plus  |     if semver.compare(qsv_semver, MINIMUM_QSV_VERSION) < 0:
datapusher-plus  |   File "/usr/lib/ckan/dpplus_venv/lib/python3.10/site-packages/semver/_deprecated.py", line 80, in wrapper
datapusher-plus  |     return func(*args, **kwargs)  # type: ignore
datapusher-plus  |   File "/usr/lib/ckan/dpplus_venv/lib/python3.10/site-packages/semver/_deprecated.py", line 112, in compare
datapusher-plus  |     return Version.parse(ver1).compare(ver2)
datapusher-plus  |   File "/usr/lib/ckan/dpplus_venv/lib/python3.10/site-packages/semver/version.py", line 646, in parse
datapusher-plus  |     raise ValueError(f"{version} is not valid SemVer string")
datapusher-plus  | ValueError:  is not valid SemVer string
datapusher-plus  | 
datapusher-plus  | During handling of the above exception, another exception occurred:
```

I've used the docker [datapusher-plus-docker](https://github.com/dathere/datapusher-plus-docker.git) , it seems like it's due to the qsvdp,  running `/usr/local/bin/qsvdp --version` also throwing error. below  
`qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory`

**Comment by jqnatividad** [comment]
Thanks @sagargg for the report.

It looks like the qsvdp bin in the docker image is not at the right version.

Regardless, we're minting a new release today of both DP+ and DP+-docker and we'll ping you once its ready.

cc @minhajuddin2510

**Comment by sagargg** [comment]
Cool. Thanks @jqnatividad . 
I am able to setup it locally, but yeah once a new version is released.  This issue can be closed.  🙏
