### ISSUE TITLE
Migrations

### ISSUE THREAD

**Issue by avdata99** [dathere/datapusher-plus#165]
Hi Team. First of all thanks for the job with this tool.

I'm using the branch `dev-v1.0` and I'm having DB troubles.
I realize that you have made changes to migrations manually.
I assumed this is a ~stablale branch and maybe I'm wrong.
It looks like you are assumming no one is using it.
I just want to flag I'm trying to use datapusher+ as a extension.

Do you have any suggestion (branch) to use this as extension in a productive environment?

**Comment by dtmarc** [comment]
Are you getting the following error? Because I am...and I'm using dev-v1.0. I'm getting this error when I attempt to run ckan -c /etc/ckan/default/ckan.ini db upgrade -p datapusher_plus and I haven't quite figured out why this is happening. 

`
Traceback (most recent call last):
  File "/usr/lib/ckan/default/bin/ckan", line 5, in <module>
    from ckan.cli.cli import ckan
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/cli/cli.py", line 14, in <module>
    from ckan.config.middleware import make_app
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/config/middleware/__init__.py", line 11, in <module>
    from ckan.config.environment import load_environment
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/config/environment.py", line 15, in <module>
    import ckan.model as model
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/model/__init__.py", line 21, in <module>
    import ckan.model.meta as meta
  File "/usr/lib/ckan/default/lib/python3.10/site-packages/ckan/model/meta.py", line 84, in <module>
    registry = orm.registry(metadata=metadata)
AttributeError: module 'sqlalchemy.orm' has no attribute 'registry'
`

**Comment by tino097** [comment]
@avdata99 the dev-v1.0 branch should be moved to the main branch soon @jqnatividad, this one is up to you 

Regarding the migrations changes, maybe it was wrong to do all those changes directly in the branch but i was rushing to make it work also in prod environment 

If you have any issues please let me know and i would try to help to resolve those

**Comment by tino097** [comment]
@dtmarc this error looks like issue with the `sqlalchemy` version 
we are using `1.4.41` that comes with CKAN core [requirements](https://github.com/ckan/ckan/blob/ckan-2.10.5/requirements.txt#L140)

**Comment by jqnatividad** [comment]
Hi all!
Sorry we've been quiet for a bit as v2.0.0 took a while to cook.

Though 2.0.0 was designed with backward compatibility in mind and was based on @tino097 's v1.x work , do let us know if we missed anything when you upgrade to v2.

**Comment by jqnatividad** [comment]
Hi @avdata99 , @dtmarc ,

It took a while, but we've totally revamped DP+.

The `dev-v1.0` branch the question references has long been merged + deleted. DP+ is now at v3.0.0a0 on `main`; v3 is production-ready with full Prefect-based flow orchestration, integration CI on every PR, and the test suite gating merges. Current installation guidance is in the README's "Development Installation" section, and `ckan db upgrade -p datapusher_plus` handles the schema.

For migrating an existing v2 (RQ-based) install, see the `ckan datapusher_plus migrate-from-rq` CLI command. If you hit specific migration trouble on a v3 install, please feel free to open a new issue.
