### ISSUE TITLE
Error on Upload to Datastore

### ISSUE THREAD

**Issue by twdbben** [dathere/datapusher-plus#174]
**Describe the bug**

Using DP+ 1.0.3, when trying to upload to datastore, receiving the following error

ckanext.datapusher_plus.auto_index_threshold is set to 3

```
2024-12-13 19:30:51,222 INFO  [ckan.lib.jobs] Worker rq:worker:6ae234f0fb174bd982728f7a563050a4 starts job f9d41496-63f2-4c7d-8ccd-095181109656 from queue "default"
2024-12-13 19:30:51,230 INFO  [ckan.config.environment] Loading static files from public
2024-12-13 19:30:51,960 INFO  [ckan.config.environment] Loading templates from /srv/app/src/ckan/ckan/templates
2024-12-13 19:30:52,638 INFO  [ckan.config.environment] Loading templates from /srv/app/src/ckan/ckan/templates
qsv version found: 1.0.0
2024-12-13 19:30:53,274 INFO  [f9d41496-63f2-4c7d-8ccd-095181109656] qsv version found: 1.0.0
Fetching from: https://dev.txwaterdatahub.org/dataset/a5b26d9c-1973-4991-9bc5-968aa9fc9c4f/resource/648791a9-d9ca-40ae-8eca-4642394c4fa1/download/simple.csv...
2024-12-13 19:30:53,405 INFO  [f9d41496-63f2-4c7d-8ccd-095181109656] Fetching from: https://dev.txwaterdatahub.org/dataset/a5b26d9c-1973-4991-9bc5-968aa9fc9c4f/resource/648791a9-d9ca-40ae-8eca-4642394c4fa1/download/simple.csv...
Rewrote resource url to: http://ckan-dev-blue/dataset/a5b26d9c-1973-4991-9bc5-968aa9fc9c4f/resource/648791a9-d9ca-40ae-8eca-4642394c4fa1/download/simple.csv
2024-12-13 19:30:53,417 INFO  [f9d41496-63f2-4c7d-8ccd-095181109656] Rewrote resource url to: http://ckan-dev-blue/dataset/a5b26d9c-1973-4991-9bc5-968aa9fc9c4f/resource/648791a9-d9ca-40ae-8eca-4642394c4fa1/download/simple.csv
File format: CSV
2024-12-13 19:30:53,867 INFO  [f9d41496-63f2-4c7d-8ccd-095181109656] File format: CSV
Downloading 0.00MB file...
2024-12-13 19:30:53,880 INFO  [f9d41496-63f2-4c7d-8ccd-095181109656] Downloading 0.00MB file...
Fetched 0.00MB file in 0.51 seconds.
2024-12-13 19:30:53,916 INFO  [f9d41496-63f2-4c7d-8ccd-095181109656] Fetched 0.00MB file in 0.51 seconds.
ANALYZING WITH QSV..
2024-12-13 19:30:53,949 INFO  [f9d41496-63f2-4c7d-8ccd-095181109656] ANALYZING WITH QSV..
Normalizing/UTF-8 transcoding CSV...
2024-12-13 19:30:53,986 INFO  [f9d41496-63f2-4c7d-8ccd-095181109656] Normalizing/UTF-8 transcoding CSV...
Identified encoding of the file: ASCII

2024-12-13 19:30:54,043 INFO  [f9d41496-63f2-4c7d-8ccd-095181109656] Identified encoding of the file: ASCII

File is not UTF-8 encoded. Re-encoding from ASCII to UTF-8
2024-12-13 19:30:54,056 INFO  [f9d41496-63f2-4c7d-8ccd-095181109656] File is not UTF-8 encoded. Re-encoding from ASCII to UTF-8
Successfully re-encoded to UTF-8
2024-12-13 19:30:54,090 INFO  [f9d41496-63f2-4c7d-8ccd-095181109656] Successfully re-encoded to UTF-8
Normalized & transcoded...
2024-12-13 19:30:54,157 INFO  [f9d41496-63f2-4c7d-8ccd-095181109656] Normalized & transcoded...
Validating CSV...
2024-12-13 19:30:54,173 INFO  [f9d41496-63f2-4c7d-8ccd-095181109656] Validating CSV...
Well-formed, valid CSV file confirmed...
2024-12-13 19:30:54,216 INFO  [f9d41496-63f2-4c7d-8ccd-095181109656] Well-formed, valid CSV file confirmed...
Checking for duplicates and if the CSV is sorted...
2024-12-13 19:30:54,226 INFO  [f9d41496-63f2-4c7d-8ccd-095181109656] Checking for duplicates and if the CSV is sorted...
Sorted: False; Unsorted breaks: 1
2024-12-13 19:30:54,256 INFO  [f9d41496-63f2-4c7d-8ccd-095181109656] Sorted: False; Unsorted breaks: 1
Checking for "database-safe" header names...
2024-12-13 19:30:54,290 INFO  [f9d41496-63f2-4c7d-8ccd-095181109656] Checking for "database-safe" header names...
"4 unsafe" header names found (['A', 'B', 'C', 'D']). Sanitizing..."
2024-12-13 19:30:54,321 INFO  [f9d41496-63f2-4c7d-8ccd-095181109656] "4 unsafe" header names found (['A', 'B', 'C', 'D']). Sanitizing..."
3  records detected...
2024-12-13 19:30:54,370 INFO  [f9d41496-63f2-4c7d-8ccd-095181109656] 3  records detected...
Inferring data types and compiling statistics...
2024-12-13 19:30:54,380 INFO  [f9d41496-63f2-4c7d-8ccd-095181109656] Inferring data types and compiling statistics...
2024-12-13 19:30:54,433 ERROR [ckanext.datapusher_plus.jobs] Datapusher Plus error: invalid literal for int() with base 10: '', Traceback (most recent call last):
  File "/srv/app/src/ckan/datapusher-plus/ckanext/datapusher_plus/jobs.py", line 264, in datapusher_plus_to_datastore
    push_to_datastore(input, job_id)
  File "/srv/app/src/ckan/datapusher-plus/ckanext/datapusher_plus/jobs.py", line 307, in push_to_datastore
    return _push_to_datastore(task_id, input, dry_run=dry_run, temp_dir=temp_dir)
  File "/srv/app/src/ckan/datapusher-plus/ckanext/datapusher_plus/jobs.py", line 905, in _push_to_datastore
    headers_cardinality.append(int(row["cardinality"]))
ValueError: invalid literal for int() with base 10: ''

2024-12-13 19:30:54,505 INFO  [ckan.lib.jobs] Worker rq:worker:6ae234f0fb174bd982728f7a563050a4 has finished job f9d41496-63f2-4c7d-8ccd-095181109656 from queue "default"
```

**To Reproduce**
I'm using a simple CSV file that has the following contents for this test

A,B,C,D
1,2,3,4
a,b,c,d
I,II,III,IV

1. Create a resource on a Dataset
2. Go to Edit Resource > Datastore
3. Click on 'Upload to Datastore'
4. Reload page to see progress and error displays in flash banner. Error also appears in log file associated with `ckan jobs worker` process

**Expected behavior**
Resource is uploaded to datastore

**Comment by twdbben** [comment]
I notice that this error is related to the 'cardinality' functionality and when I do a `qsvdp --cardinality` on the command line it is giving me `Unknown flag: '--cardinality'`

`qsvdp -version` tells me `qsvdp 1.0.0-mimalloc-Luau 0.653;self_update-2-2;5.97 GiB-0 B-2.87 GiB-7.46 GiB (Unknown_target compiled with Rust 1.83) installed`

**Comment by twdbben** [comment]
Nevermind, I see now that the command is `qsv stats --cardinality` and that appears to be working.

**Comment by twdbben** [comment]
In case it's helpful, here's some info on what qsvdp is returning 
```
root@ckan-dev-blue-ffbd498c4-kxpf5:/srv/app# cat simple.csv
A,B,C,D
1,2,3,4
a,b,c,d
I,II,III,IV
root@ckan-dev-blue-ffbd498c4-kxpf5:/srv/app# qsvdp stats --cardinality simple.csv
field,type,is_ascii,sum,min,max,range,sort_order,min_length,max_length,sum_length,avg_length,mean,sem,stddev,variance,cv,nullcount,max_precision,sparsity,cardinality,qsv__value
A,String,true,,1,a,,Unsorted,1,1,3,1,,,,,,0,,0,3,
B,String,true,,2,b,,Unsorted,1,2,4,1.3333,,,,,,0,,0,3,
C,String,true,,3,c,,Unsorted,1,3,5,1.6667,,,,,,0,,0,3,
D,String,true,,4,d,,Unsorted,1,2,4,1.3333,,,,,,0,,0,3,
qsv__rowcount,,,,,,,,,,,,,,,,,,,,,3
qsv__columncount,,,,,,,,,,,,,,,,,,,,,4
qsv__filesize_bytes,,,,,,,,,,,,,,,,,,,,,36
qsv__fingerprint_hash,,,,,,,,,,,,,,,,,,,,,ec91001e752c9fca49199b3b3f905754d14058b5a630ca8606f5a72e2795dce2
```

The way I'm interpreting this, the rows in the qsvdp output that start with qsv_ don't have a cardinality value, which is then causing the `ValueError: invalid literal for int() with base 10: ''` when [this loop](https://github.com/dathere/datapusher-plus/blob/8c86c1e2301d847fd51979eaf82d4c82073214f7/ckanext/datapusher_plus/jobs.py#L899-L905) encounters those rows.

**Comment by jqnatividad** [comment]
Thanks for the detailed report @twdbben.

This is a bug caused by the new dataset-level stats introduced with qsv 1.0.0.

As you can see, there are four additional internal stats computed by v1.0.0 - qsv__rowcount, qsv__columncount, qsv_filesize_bytes and qsv__fingerprint_hash.

These four additional columns are actually paving the way for some additional DP+ DRUF capabilities I'm working on, but I neglected to update DP+.

@tino097 is putting in a quick fix and it should be ready shortly.

**Comment by jqnatividad** [comment]
For now @twdbben , just use qsvdp v0.138.0 while @tino097 works on the quick fix.

`cargo install qsv@0.138.0 --locked --bin qsvdp -F datapusher_plus,luau --force`

**Comment by tino097** [comment]
@jqnatividad i've just pushed the commit with the fix on the `dev-v1.0`

**Comment by jqnatividad** [comment]
Closing this now that 2.0.0 is released with the fixes.
