### ISSUE TITLE
Containerfile does miss config module

### ISSUE THREAD

**Issue by BonaBeavis** [dathere/datapusher-plus#76]
Could not get the containerfile for version 0.10.1 to run, issue is here:

```
Traceback (most recent call last):
  File "/usr/lib/ckan/datapusher/venv/bin/datapusher_initdb", line 11, in <module>
    load_entry_point('datapusher-plus', 'console_scripts', 'datapusher_initdb')()
  File "/usr/lib/ckan/datapusher/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/ckan/datapusher/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2852, in load_entry_point
    return ep.load()
  File "/usr/lib/ckan/datapusher/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2443, in load
    return self.resolve()
  File "/usr/lib/ckan/datapusher/venv/lib/python3.8/site-packages/pkg_resources/__init__.py", line 2449, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/ckan/datapusher/code/datapusher/main.py", line 5, in <module>
    from config import config
ModuleNotFoundError: No module named 'config'
```

**Comment by jqnatividad** [comment]
Closing as obsolete. DP+ v0.10.1 (2023) used a standalone webservice container with its own `initdb` entry point — that whole deployment model went away in the v2.0 refactor ("replaces the legacy Datapusher webservice with a full CKAN extension" per CLAUDE.md). DP+ v3 is now a CKAN extension installed into CKAN's own venv; there's no separate `datapusher_initdb` console script.

For containerized deployments, see `docker-compose.integration.yaml` + `Dockerfile.worker` (the Prefect worker image, based on `ckan/ckan-dev:2.11`) — `scripts/integration-up` brings the whole stack up. If you hit a packaging error with the current container setup, please open a fresh issue with the build / run logs.
